
url: https://lasica.co
title: kubalasecki
email: kubalasecki@gmail.com
description: > # "Bla Bla Bla"

markdown: kramdown
permalink: pretty

social:
  - title: skype
    url: #
    id: SkypeButton_Chat_kubica1988
  - title: github
    url: https://github.com/kubalasecki
    id: githublink
  - title: linkedin
    url: https://pl.linkedin.com/in/kubalasecki
    id: linkedinlink
